package main

// ============================================================================
// airports.go — METAR airport list served at /airports
// ----------------------------------------------------------------------------
// The list is NOT the full AWC station registry (~7.7k stations that *could*
// report). Instead it reflects the stations that actually reported METAR
// recently: we fetch NOAA AWC's bulk metar cache (the same endpoint as
// meteolibre_datasetgen's fetch_latest_global, ~5k stations reporting in the
// previous hour) and intersect it with the embedded registry
// (data/airports.json, regenerated by scripts/fetch_airports.py) for
// station names/countries.
//
// The snapshot is refreshed in the background every AIRPORTS_REFRESH_MINUTES
// (default 30) and stations older than AIRPORTS_MAX_REPORT_AGE_HOURS (default
// 3) are dropped. If a fetch has never succeeded, the embedded registry is
// served as a fallback so the endpoint stays functional.
// ============================================================================

import (
	"bytes"
	"compress/gzip"
	"crypto/md5"
	_ "embed"
	"encoding/csv"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"sort"
	"strconv"
	"sync"
	"time"
)

//go:embed data/airports.json
var airportsJSON []byte

const defaultAWCUrl = "https://aviationweather.gov/data/cache/metars.cache.csv.gz"

var (
	airportsAWCUrl    = envOr("AIRPORTS_AWC_URL", defaultAWCUrl)
	airportsRefresh   = time.Duration(atoiOr(envOr("AIRPORTS_REFRESH_MINUTES", "30"), 30)) * time.Minute
	airportsMaxAge, _ = time.ParseDuration(envOr("AIRPORTS_MAX_REPORT_AGE", "3h"))
)

// airportEntry is one station in the /airports payload.
type airportEntry struct {
	ICAO    string  `json:"icao"`
	Name    string  `json:"name"`
	Lat     float64 `json:"lat"`
	Lon     float64 `json:"lon"`
	Country string  `json:"country"`
}

type airportsRegistryFile struct {
	GeneratedAt string         `json:"generated_at"`
	Count       int            `json:"count"`
	Airports    []airportEntry `json:"airports"`
}

// airportSnapshot is an immutable, fully rendered /airports response.
type airportSnapshot struct {
	fetchedAt time.Time
	latestObs time.Time // newest observation_time in the source
	count     int
	etag      string
	payload   []byte // JSON
	gzPayload []byte // gzipped JSON
	live      bool   // true when built from the AWC bulk cache
}

var (
	airportsMu       sync.RWMutex
	airportsRegistry map[string]airportEntry // icao → entry (name/country source)
	airportsCurrent  *airportSnapshot       // nil until first build
	airportsInitOnce sync.Once
)

// airportsInit parses the embedded registry and starts the background
// refresher (runs once, on first /airports request — keeps unit tests light).
func airportsInit() {
	airportsInitOnce.Do(func() {
		var reg airportsRegistryFile
		if err := json.Unmarshal(airportsJSON, &reg); err != nil {
			log.Printf("[airports] failed to parse embedded registry: %v", err)
			airportsRegistry = map[string]airportEntry{}
		} else {
			airportsRegistry = make(map[string]airportEntry, len(reg.Airports))
			for _, a := range reg.Airports {
				airportsRegistry[a.ICAO] = a
			}
		}

		// Serve the registry immediately (fallback), then refresh live.
		airportsMu.Lock()
		airportsCurrent = buildSnapshot(reg.Airports, time.Time{}, false)
		airportsMu.Unlock()

		go airportsRefreshLoop()
	})
}

func airportsRefreshLoop() {
	refresh := func() {
		snap, err := fetchAirportsSnapshot()
		if err != nil {
			log.Printf("[airports] refresh failed (keeping stale list): %v", err)
			return
		}
		airportsMu.Lock()
		airportsCurrent = snap
		airportsMu.Unlock()
	}

	refresh()
	t := time.NewTicker(airportsRefresh)
	defer t.Stop()
	for range t.C {
		refresh()
	}
}

// fetchAirportsSnapshot downloads the AWC bulk metar cache and builds the
// live airport list (stations with a recent METAR/SPECI report).
func fetchAirportsSnapshot() (*airportSnapshot, error) {
	client := &http.Client{Timeout: 60 * time.Second}
	req, err := http.NewRequest("GET", airportsAWCUrl, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "meteolibre-global-server/1.0 (airport list)")

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("AWC returned %d", resp.StatusCode)
	}

	zr, err := gzip.NewReader(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("gzip: %v", err)
	}
	defer zr.Close()

	// Read + parse CSV. NOTE: the AWC header has duplicate column names
	// (sky_cover x4 …) — csv.Reader doesn't care, we just map the first
	// occurrence of each name we need.
	recs, err := csv.NewReader(zr).ReadAll()
	if err != nil && err != io.EOF {
		return nil, fmt.Errorf("csv: %v", err)
	}
	if len(recs) < 2 {
		return nil, fmt.Errorf("empty AWC cache")
	}

	colIdx := func(name string) int {
		for i, h := range recs[0] {
			if h == name {
				return i
			}
		}
		return -1
	}
	iStation := colIdx("station_id")
	iTime := colIdx("observation_time")
	iLat := colIdx("latitude")
	iLon := colIdx("longitude")
	iType := colIdx("metar_type")
	if iStation < 0 || iTime < 0 || iLat < 0 || iLon < 0 || iType < 0 {
		return nil, fmt.Errorf("unexpected AWC cache schema")
	}

	now := time.Now().UTC()
	type stEntry struct {
		obs time.Time
		lat float64
		lon float64
	}
	stations := make(map[string]stEntry)
	var latestObs time.Time

	for _, r := range recs[1:] {
		if len(r) <= iType {
			continue
		}
		// Keep routine + special METARs (mirrors fetch_latest_global).
		if t := r[iType]; t != "METAR" && t != "SPECI" {
			continue
		}
		icao := r[iStation]
		obs, err := time.Parse(time.RFC3339, r[iTime])
		if err != nil {
			continue
		}
		lat, err1 := strconv.ParseFloat(r[iLat], 64)
		lon, err2 := strconv.ParseFloat(r[iLon], 64)
		if err1 != nil || err2 != nil {
			continue
		}
		if age := now.Sub(obs); age > airportsMaxAge || age < -30*time.Minute {
			continue
		}
		if prev, ok := stations[icao]; !ok || obs.After(prev.obs) {
			stations[icao] = stEntry{obs: obs, lat: lat, lon: lon}
		}
		if obs.After(latestObs) {
			latestObs = obs
		}
	}

	if len(stations) < 100 {
		return nil, fmt.Errorf("suspiciously few stations (%d) — keeping stale list", len(stations))
	}

	entries := make([]airportEntry, 0, len(stations))
	for icao, st := range stations {
		e := airportEntry{ICAO: icao, Name: icao, Lat: st.lat, Lon: st.lon}
		if reg, ok := airportsRegistry[icao]; ok {
			e.Name = reg.Name
			e.Country = reg.Country
			// Prefer live coordinates; fall back to registry on junk values.
			if e.Lat < -90 || e.Lat > 90 || e.Lon < -180 || e.Lon > 180 {
				e.Lat, e.Lon = reg.Lat, reg.Lon
			}
		}
		entries = append(entries, e)
	}

	return buildSnapshot(entries, latestObs, true), nil
}

// buildSnapshot renders the JSON payload (+gzip +ETag) for /airports.
func buildSnapshot(entries []airportEntry, latestObs time.Time, live bool) *airportSnapshot {
	sort.Slice(entries, func(i, j int) bool { return entries[i].ICAO < entries[j].ICAO })

	out := struct {
		GeneratedAt string         `json:"generated_at"`
		Source      string         `json:"source"`
		Count       int            `json:"count"`
		Airports    []airportEntry `json:"airports"`
	}{
		GeneratedAt: time.Now().UTC().Format("2006-01-02T15:04:05Z"),
		Source:      airportsAWCUrl,
		Count:       len(entries),
		Airports:    entries,
	}
	payload, err := json.Marshal(out)
	if err != nil {
		payload = []byte(`{"count":0,"airports":[]}`)
	}

	var gz bytes.Buffer
	zw := gzip.NewWriter(&gz)
	zw.Write(payload)
	zw.Close()

	sum := md5.Sum(payload)
	return &airportSnapshot{
		fetchedAt: time.Now().UTC(),
		latestObs: latestObs,
		count:     len(entries),
		etag:      fmt.Sprintf(`"%s"`, hex.EncodeToString(sum[:])),
		payload:   payload,
		gzPayload: gz.Bytes(),
		live:      live,
	}
}

// handleAirports serves the airport list (live snapshot when available,
// embedded registry as fallback). Payload is pre-rendered per refresh.
func handleAirports(w http.ResponseWriter, r *http.Request) {
	airportsInit()

	airportsMu.RLock()
	snap := airportsCurrent
	airportsMu.RUnlock()
	if snap == nil {
		writeError(w, 500, "airport list unavailable")
		return
	}

	w.Header().Set("ETag", snap.etag)
	w.Header().Set("X-Airports-Live", strconv.FormatBool(snap.live))
	if snap.latestObs.IsZero() {
		w.Header().Set("X-Airports-Latest-Obs", "")
	} else {
		w.Header().Set("X-Airports-Latest-Obs", snap.latestObs.Format(time.RFC3339))
	}
	if match := r.Header.Get("If-None-Match"); match == snap.etag {
		w.WriteHeader(http.StatusNotModified)
		return
	}

	// Snapshots are immutable; a 15 min browser cache keeps clicks snappy
	// while staying close to the hourly AWC cadence.
	setCacheHeaders(w, 900)

	if bytes.Contains([]byte(r.Header.Get("Accept-Encoding")), []byte("gzip")) {
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Content-Encoding", "gzip")
		w.Write(snap.gzPayload)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(snap.payload)
}
